Squashed-for-review parsing of activities for track_oracle.
*Note that this branch tracks dev/kpf-track-oracle-activities,
unsquashed.*

This larger-than-I-would-have-expected set of commits all leads up to
this command functioning: (broken across lines for clarity):

   $ track_oracle/example/kpf_activity_example
       -in-geom ~/tmp/v3-geom.yml
       -in-act ~/tmp/v3-act.yml
       -out ~/tmp/bar

...in other words, track_oracle can now read and write KPF geometry
and activities.

1) A new KPF packet "cset" was added to represent classification
vectors; see kpf_example_simple_classifier (below) for an example.

2) The kpf_activity_example and kpf_example_simple_classifier binaries
was added.

3) The kpf_generic_reader binary was added.

4) Now requires the V3 KPF schema wrapper.

5) The KPF parser was basically completely rewritten (not my proudest
moment...)

Originally, KPF was a plaintext format. The late addition of YAML
solved a lot of problems (nesting structures, for example) but I
didn't think it through fully; in particular, the YAML record

     - { key1: val1, key2: val2, key3: val3 }

...is a map; you can't guarantee what order you'll see key1, key2, and
key3 as you iterate through the nodes. The old plaintext parser was
built around an ordered sequence of tokens, which failed miserably
once the record got large enough (i.e. activities). So it was ripped
out and rewritten.

Along the way the schema wrapper was added, bumping KPF's verison up
to V3.

This adds a *set* of confidence values as a map:

   cset17: { other: 0.1, person: 0.3, vehicle: 0.6, },

...now it could be argued that across thousands or millions of lines,
repeating the tags is wasteful, and we should have a cvec type:

   cvec17: { 0.1, 0.3, 0.6 }

...with the tags made explicit elsewhere. This is probably true,
but I'm really really afraid of slicing-n-dicing files and losing that
connection.

So now you can run (shown w/ abbreviated log messages):

$ track_reader_example -f ~/tmp/cset-geom.yml -kpf-g ~/tmp/quux.yml
INFO: Could not load default logger factory. Using built-in logger.
ERROR: VPD_EVENT: [...usual VPD error message ]
INFO: KPF geometry YAML load start
INFO: KPF geometry YAML load end
INFO: KPF geom parsing warnings begin
INFO: Ignoring TS domain 1 : count 1
INFO: KPF geom parsing warnings end
INFO: Loaded 1 tracks, format: kpf-geom
INFO: 1 tracks contain...
INFO: 1 / 1:	__frame_list
INFO: 1 / 1:	external_id
INFO: 1 / 1:	track_format
INFO: 1 / 1:	track_source_file_id
INFO: 1 frames contain...
INFO: 1 / 1:	__parent_track
INFO: 1 / 1:	detection_id
INFO: 1 / 1:	bounding_box
INFO: 1 / 1:	frame_number
INFO: 1 / 1:	cset_17
INFO: 1 / 1:	kv_src
INFO: KPF writer: adding optional cset/17
INFO: KPF writer: adding optional KV src
INFO: Wrote KPF geometry to /Users/collinsr/tmp/quux.yml success: 1

...and the input and output files are the same, including the cset.